# Disable services we don't need. 

# Remove packages we don't need.
- name: Apt Unused Packages
  apt:
    name:
      - snapd
      - multipath-tools
      - popularity-contest
      - byobu
      - packagekit
      - cloud-init # No longer needed after first boot
      - plymouth # Boot screen service
      - plymouth-theme-ubuntu-text
      - apport # Crash report tool
      - lvm2 # Not using LVM
      - udisks2 # Not using disk automount
      - fwupd # Not needed on raspberry pi
      - lxd-agent-loader 
      - modemmanager
      - sosreport
    state: absent
    purge: yes
    autoclean: yes
    autoremove: yes