---
# Install tools useful for administrators
- name: Install show_dhcp_leases script
  copy:
    src: tools/show_dhcp_leases.py
    dest: /usr/local/bin/show_dhcp_leases
    owner: root
    group: root
    mode: '0755'
  tags:
    - tools

- name: Ensure dnspython is installed (apt)
  apt:
    name: python3-dnspython
    state: present
    update_cache: yes
  tags:
    - tools
