name: Ansible Lint  # feel free to pick your own name

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v2

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r requirements.yml

      - name: Lint Ansible Playbook
        # replace "master" with any valid ref
        uses: ansible/ansible-lint@v26.1.1
        with:
          # [required]
          # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
          # or valid Ansible directories according to the Ansible role
          # directory structure.
          # If you want to lint multiple ansible files, use the following syntax
          # targets: |
          #   playbook_1.yml
          #   playbook_2.yml
          targets: "playbook.yml"
          # [optional]
          # Path to requirements.yml for roles/collections
          requirements_file: "requirements.yml"
          # [optional]
          # Arguments to be passed to the ansible-lint
          args: ""
